language: rust
after_success:
  - bash deploy.sh
env:
  global:
    secure: Aec+N5y5OKBTrdj75NhLIBElPeEzlap2mlU8vG3uVSvIoIeGbqesddh5wRK2r5+GkJzhUbI0XnP/LUdWAYDdALA1ZijrXs0NY2bxJCnUM/X9qT04f4zVgxjcKH0BbZaP/f7yQHGzyz+6EQxj79bMBKYUYB2KCUIuBEOTpR5+RFvo8bslab3sQ3vTXZhE3OJVkWGPzL5kEs47OjUPhIDCOB6xaXoB4ewY9iWlMAeaMMb8X2Q6q+qG7sLsaEE815MI93G34MIJR7d7JNY39DKVcCVumC2i11J4pqkpNt1H8pJ44QufyBlfkkssPWtLAXGNrP81Z64RyKvVaZfMxbyU0aKMyesnMxPLzWvM+mLL+DZMnyVHM71Xnp22QhDV6PnLyl5wY/05z8X/XgvKdiDM5NFQAh4+UxagBQaX+VPc3lQOX+o5DjxFPXXZjkd+397a8BiBgD5YmrM6CFyZQfGyh80SDdi+P89HpqGRqeBrIRzeWD3vJ9IWX+pGrfa+9ZMlJ4Iydbg/SDpEsEgKtRF0vFETylKZ2tS5Ll1OJE5+Agf52mG1wKOTWlBnUtoggom3k2HEGmxkSqwy0Z25yN/dINhkUF+ZwKEkONyiJ/yNgjltzc4P8pdmmMYxfBrb5VprTlLqyGZkAwIcuPM6anfZnavFtZ5L7BrC/6PDFyyVUpU=
