[package]
name = "modulo_ui"
version = "0.1.0"
authors = ["Connor Brewster <connor.brewster@eagles.oc.edu>", "Caleb Wren <caleb_wren@me.com>"]
license = "MIT"

[dependencies]
modulo = { path = "../modulo" }
modulo_traits = { path = "../modulo_traits" }
